### ISSUE TITLE
java.lang.IllegalStateException: Offset is unspecified

### ISSUE THREAD

**Issue by aabhashshakya** [commandiron/WheelPickerCompose#30]
Affected devices as far as I have tested: Samsung Galaxy S21 Ultra 5G (Android 13), Xiaomi Mi A2 Lite(Android 10)
Unaffected devices: TCL 20S

Was working fine before but now out of nowhere got this issue:

`androidx.compose.ui.geometry.Offset.getX-impl Offset.java:28
androidx.compose.ui.graphics.Matrix.map-impl Matrix.java
androidx.compose.ui.platform.RenderNodeLayer.mapBounds RenderNodeLayer.java
androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release NodeCoordinator.java
androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release$default NodeCoordinator.java
androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf NodeCoordinator.java
androidx.compose.ui.layout.LayoutCoordinates.localBoundingBoxOf$default LayoutCoordinates.java
androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInRoot LayoutCoordinatesKt.java
androidx.compose.ui.node.SemanticsModifierNodeKt.touchBoundsInRoot SemanticsModifierNodeKt.java
androidx.compose.ui.semantics.SemanticsNode.getTouchBoundsInRoot SemanticsNode.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive AndroidComposeViewAccessibilityDelegateCompat_androidKt.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive AndroidComposeViewAccessibilityDelegateCompat_androidKt.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive AndroidComposeViewAccessibilityDelegateCompat_androidKt.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive AndroidComposeViewAccessibilityDelegateCompat_androidKt.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive AndroidComposeViewAccessibilityDelegateCompat_androidKt.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap AndroidComposeViewAccessibilityDelegateCompat_androidKt.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes AndroidComposeViewAccessibilityDelegateCompat.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createEvent$ui_release AndroidComposeViewAccessibilityDelegateCompat.java:34
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendEventForVirtualView AndroidComposeViewAccessibilityDelegateCompat.java:11
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendEventForVirtualView$default AndroidComposeViewAccessibilityDelegateCompat.java:6
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendSubtreeChangeAccessibilityEvents AndroidComposeViewAccessibilityDelegateCompat.java
androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.boundsUpdatesEventLoop AndroidComposeViewAccessibilityDelegateCompat.java
androidx.compose.ui.platform.AndroidComposeView.boundsUpdatesEventLoop AndroidComposeView.java
androidx.compose.ui.platform.WrappedComposition$setContent$1$1$1.invokeSuspend WrappedComposition.java
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith BaseContinuationImpl.java:8
kotlinx.coroutines.DispatchedTask.run DispatchedTask.java:100
androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch AndroidUiDispatcher.java
androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch AndroidUiDispatcher.java
androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run AndroidUiDispatcher.java:2
android.os.Handler.handleCallback Handler.java:883`

Useful note: had gotten this about a week ago when building the app:
  > Could not resolve com.github.commandiron:WheelPickerCompose:1.1.10.
         > Could not get resource 'https://jitpack.io/com/github/commandiron/WheelPickerCompose/1.1.10/WheelPickerCompose-1.1.10.pom'.
            > Could not GET 'https://jitpack.io/com/github/commandiron/WheelPickerCompose/1.1.10/WheelPickerCompose-1.1.10.pom'.
               > Read timed out

**Comment by commandiron** [comment]
can you share your code sniplet

**Comment by pawankhandal52** [comment]
I am also getting the same issue. in my production APP


Fatal Exception: java.lang.IllegalStateException: Offset is unspecified
       at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:67)
       at androidx.compose.ui.geometry.OffsetKt.isFinite-k-4lQ0M(Offset.kt)
       at androidx.compose.ui.node.NodeCoordinator.withinLayerBounds-k-4lQ0M(NodeCoordinator.kt:1013)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:525)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitNear-JHbHoSQ(NodeCoordinator.kt:619)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:534)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:597)
       at androidx.compose.ui.node.NodeCoordinator.access$getTmpLayerPositionalProperties$cp(NodeCoordinator.kt)
       at androidx.compose.ui.node.NodeCoordinator.access$hit-1hIXUjU(NodeCoordinator.kt)
       at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt:601)
       at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt)
       at androidx.compose.ui.node.HitTestResult.hitInMinimumTouchTarget(HitTestResult.kt:116)
       at androidx.compose.ui.node.HitTestResult.hit(HitTestResult.kt:96)
       at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:599)
       at androidx.compose.ui.node.NodeCoordinator.access$getTmpLayerPositionalProperties$cp(NodeCoordinator.kt)
       at androidx.compose.ui.node.NodeCoordinator.access$hit-1hIXUjU(NodeCoordinator.kt)
       at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt:601)
       at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt)
       at androidx.compose.ui.node.HitTestResult.hitInMinimumTouchTarget(HitTestResult.kt:116)
       at androidx.compose.ui.node.HitTestResult.hit(HitTestResult.kt:96)
       at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:599)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:548)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:597)
       at androidx.compose.ui.node.NodeCoordinator.access$getTmpLayerPositionalProperties$cp(NodeCoordinator.kt)
       at androidx.compose.ui.node.NodeCoordinator.access$hit-1hIXUjU(NodeCoordinator.kt)
       at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt:601)
       at androidx.compose.ui.node.NodeCoordinator$hit$1.invoke(NodeCoordinator.kt)
       at androidx.compose.ui.node.HitTestResult.hitInMinimumTouchTarget(HitTestResult.kt:116)
       at androidx.compose.ui.node.HitTestResult.hit(HitTestResult.kt:96)
       at androidx.compose.ui.node.NodeCoordinator.hit-1hIXUjU(NodeCoordinator.kt:599)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:548)
       at androidx.compose.ui.node.NodeCoordinator.hitTestChild-YqVAtuI(NodeCoordinator.kt:697)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.NodeCoordinator$Companion$PointerInputSource$1.childHitTest-YqVAtuI(NodeCoordinator.kt:1254)
       at androidx.compose.ui.node.InnerNodeCoordinator.hitTestChild-YqVAtuI(InnerNodeCoordinator.kt:187)
       at androidx.compose.ui.node.NodeCoordinator.hitTest-YqVAtuI(NodeCoordinator.kt:545)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release(LayoutNode.kt:863)
       at androidx.compose.ui.node.LayoutNode.hitTest-M_7yMNQ$ui_release$default(LayoutNode.kt:856)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:84)
       at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1329)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1275)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1214)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3049)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3049)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3049)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3049)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2636)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1980)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:844)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:557)
       at android.view.View.dispatchPointerEvent(View.java:12123)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5119)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4910)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4404)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4474)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4432)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4574)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4440)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4631)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4404)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4474)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4432)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4440)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4404)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7070)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7044)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6995)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:195)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:333)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)

**Comment by BadKiko** [comment]
Same error 

FATAL EXCEPTION: main
                                                                                                    Process: com.kiko.meditationapp, PID: 1464
                                                                                                    java.lang.IllegalStateException: Offset is unspecified
                                                                                                    	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:67)
                                                                                                    	at androidx.compose.ui.graphics.Matrix.map-impl(Matrix.kt:86)
                                                                                                    	at androidx.compose.ui.platform.RenderNodeLayer.mapBounds(RenderNodeLayer.android.kt:335)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:946)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release$default(NodeCoordinator.kt:924)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf(NodeCoordinator.kt:812)
                                                                                                    	at androidx.compose.ui.layout.LayoutCoordinates.localBoundingBoxOf$default(LayoutCoordinates.kt:94)
                                                                                                    	at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInRoot(LayoutCoordinates.kt:128)
                                                                                                    	at androidx.compose.ui.node.SemanticsModifierNodeKt.touchBoundsInRoot(SemanticsModifierNode.kt:62)
                                                                                                    	at androidx.compose.ui.semantics.SemanticsNode.getTouchBoundsInRoot(SemanticsNode.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3272)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3291)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3291)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3291)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap$findAllSemanticNodesRecursive(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3291)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat_androidKt.getAllUncoveredSemanticsNodesToMap(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3322)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.getCurrentSemanticsNodes$ui_release(AndroidComposeViewAccessibilityDelegateCompat.android.kt:383)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.createEvent$ui_release(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1439)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendEventForVirtualView(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1391)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendEventForVirtualView$default(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1381)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.sendSubtreeChangeAccessibilityEvents(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2151)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.boundsUpdatesEventLoop(AndroidComposeViewAccessibilityDelegateCompat.android.kt:2069)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$boundsUpdatesEventLoop$1.invokeSuspend(Unknown Source:18)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
2023-04-25 16:45:16.327  1464-1464  AndroidRuntime          com.kiko.meditationapp               E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@34c2888, androidx.compose.runtime.BroadcastFrameClock@cf6e221, StandaloneCoroutine{Cancelling}@48a8646, AndroidUiDispatcher@408b007]
2023-04-25 16:45:16.357  1464-1464  Process                 com.kiko.meditationapp

**Comment by IgorRumble** [comment]
Same exception:
java.lang.IllegalStateException: Offset is unspecified

Any ideas how to fix it?

**Comment by BadKiko** [comment]
> 

Idk, on emulator all works, but on my phone its throw this error

**Comment by BadKiko** [comment]
I fix it but i dont know how in my old app its work but in new generated it dont work

this depend's to get work this


dependencies {
    implementation 'com.github.commandiron:WheelPickerCompose:1.1.10'

    implementation 'com.github.devsideal:VectorChildFinder:1.0.0'
    implementation("io.github.raamcosta.compose-destinations:core:1.8.38-beta")
    ksp("io.github.raamcosta.compose-destinations:ksp:1.8.38-beta")

    implementation "androidx.room:room-runtime:2.5.0-rc01"
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.work:work-runtime-ktx:2.7.1'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    kapt "androidx.room:room-compiler:$room_version"
    implementation 'androidx.compose.material3:material3:1.0.1'
    implementation "androidx.compose.material:material:1.3.1"
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation "androidx.compose.ui:ui:1.3.2"
    implementation "androidx.compose.ui:ui-tooling-preview:1.4.0-alpha03"
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'
    implementation 'androidx.activity:activity-compose:1.6.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
    androidTestImplementation 'androidx.test.ext:junit:1.1.4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.3.2"
    debugImplementation "androidx.compose.ui:ui-tooling:1.3.2"
}

in android  
composeOptions {
        kotlinCompilerExtensionVersion = "1.3.2"
    }

**Comment by IgorRumble** [comment]
@BadKiko do you know which exactly of these dependencies fixed the problem?

**Comment by BadKiko** [comment]
unfortunately no, I didn't have time to figure it out and I just copied everything from the old project

**Comment by BadKiko** [comment]
Maybe you can find the right dependency

**Comment by commandiron** [comment]
Hi, what is your api level?

**Comment by IgorRumble** [comment]
@commandiron 
implementation 'com.github.commandiron:WheelPickerCompose:1.1.10'
 def compose_version = "1.5.0-alpha03"

**Comment by SUIFENGSK** [comment]
Hi @commandiron 
Can this new version be released soon? I need it for my project, which is due in 2 weeks. I would greatly appreciate it if you could do that. :)) (It works in the emulator but not on my phone)

**Comment by commandiron** [comment]
The issue has been fixed in [this](https://github.com/commandiron/WheelPickerCompose/releases/tag/1.1.11) version.
